agent: enabled=1
boot: order=ide1;ide3
ciuser: Administrator
cores: 6
cpu: host,hidden=1,flags=+aes
ide1: local:101/vm-101-disk-0.qcow2,size=150G,serial=WD-WX51A8080436,model=WDC_WD1600BEVT-22ZCT0
ide2: local:101/vm-101-cloudinit.qcow2,media=cdrom,size=4M
ide3: local:iso/virtio-win.iso,media=cdrom,size=856810K
machine: pc-i440fx-10.1
memory: 6145
meta: creation-qemu=10.0.2,ctime=1762539126
name: win10-shared-101
net0: e1000=00:1B:21:3A:4B:5C,bridge=vmbr3,firewall=1
numa: 0
ostype: win10
scsihw: virtio-scsi-single
sockets: 1
tablet: 1
vmgenid: e1c39deb-7b61-4784-bb80-5a153bcef3bb
args: -smbios type=0,vendor="American Megatrends Inc.",version=3801,date=03/11/2022 -smbios type=1,uuid=483582ca-e738-4226-aa11-8fa9cc017e49,manufacturer="ASUSTeK COMPUTER INC.",product="PRIME X570-PRO",version="Rev 1.xx",serial=M5100CS0A1B2C -smbios type=2,manufacturer="ASUSTeK COMPUTER INC.",product="PRIME X570-PRO",version="Rev X.0x",serial=210798765432109 -smbios type=3,manufacturer="ASUSTeK COMPUTER INC.",version="Rev 1.0",serial=CHS210798765
